
STATION_LIMITS_ARRAYS = [
    ["SW_VERSION", None, None, 95],
    ["EQUIP_VERSION", None, None, 96],
    ["DUT_ScreenOnRetries", 0, 5, 97],
    ["DUT_ScreenOnStatus", True, True, 98],
    ["DUT_CancelByOperator", False, False, 99],
    ["DUT_AlignmentSuccess", True, True, 100],

    ["Test_RAW_IMAGE_SAVE_SUCCESS_normal_W255", True, True, 10001],
    ["Test_RAW_IMAGE_SAVE_SUCCESS_normal_G127", True, True, 10002],
    ["Test_RAW_IMAGE_SAVE_SUCCESS_normal_W000", True, True, 10003],
    ["Test_RAW_IMAGE_SAVE_SUCCESS_normal_RGB", True, True, 10004],
    ["Test_RAW_IMAGE_SAVE_SUCCESS_normal_R255", True, True, 10005],
    ["Test_RAW_IMAGE_SAVE_SUCCESS_normal_G255", True, True, 10006],
    ["Test_RAW_IMAGE_SAVE_SUCCESS_normal_B255", True, True, 10007],
    ["Test_RAW_IMAGE_SAVE_SUCCESS_normal_GreenContrast", True, True, 10008],
    ["Test_RAW_IMAGE_SAVE_SUCCESS_normal_WhiteContrast", True, True, 10009],
    ["Test_RAW_IMAGE_SAVE_SUCCESS_normal_GreenSharpness", True, True, 10010],
    ["Test_RAW_IMAGE_SAVE_SUCCESS_normal_GreenDistortion", True, True, 10011],
    ["Test_RAW_IMAGE_SAVE_SUCCESS_extendedz_W255", True, True, 10012],
    ["Test_RAW_IMAGE_SAVE_SUCCESS_extendedz_G127", True, True, 10013],
    ["Test_RAW_IMAGE_SAVE_SUCCESS_extendedz_W000", True, True, 10014],
    ["Test_RAW_IMAGE_SAVE_SUCCESS_extendedz_RGB", True, True, 10015],
    ["Test_RAW_IMAGE_SAVE_SUCCESS_extendedz_R255", True, True, 10016],
    ["Test_RAW_IMAGE_SAVE_SUCCESS_extendedz_G255", True, True, 10017],
    ["Test_RAW_IMAGE_SAVE_SUCCESS_extendedz_B255", True, True, 10018],
    ["Test_RAW_IMAGE_SAVE_SUCCESS_extendedz_GreenContrast", True, True, 10019],
    ["Test_RAW_IMAGE_SAVE_SUCCESS_extendedz_WhiteContrast", True, True, 10020],
    ["Test_RAW_IMAGE_SAVE_SUCCESS_extendedz_GreenSharpness", True, True, 10021],
    ["Test_RAW_IMAGE_SAVE_SUCCESS_extendedz_GreenDistortion", True, True, 10022],
    ["Test_RAW_IMAGE_SAVE_SUCCESS_extendedxpos_W255", True, True, 10023],
    ["Test_RAW_IMAGE_SAVE_SUCCESS_extendedxpos_G127", True, True, 10024],
    ["Test_RAW_IMAGE_SAVE_SUCCESS_extendedxpos_W000", True, True, 10025],
    ["Test_RAW_IMAGE_SAVE_SUCCESS_extendedxpos_RGB", True, True, 10026],
    ["Test_RAW_IMAGE_SAVE_SUCCESS_extendedxpos_R255", True, True, 10027],
    ["Test_RAW_IMAGE_SAVE_SUCCESS_extendedxpos_G255", True, True, 10028],
    ["Test_RAW_IMAGE_SAVE_SUCCESS_extendedxpos_B255", True, True, 10029],
    ["Test_RAW_IMAGE_SAVE_SUCCESS_extendedxpos_GreenContrast", True, True, 10030],
    ["Test_RAW_IMAGE_SAVE_SUCCESS_extendedxpos_WhiteContrast", True, True, 10031],
    ["Test_RAW_IMAGE_SAVE_SUCCESS_extendedxpos_GreenSharpness", True, True, 10032],
    ["Test_RAW_IMAGE_SAVE_SUCCESS_extendedxpos_GreenDistortion", True, True, 10033],
    ["Test_RAW_IMAGE_SAVE_SUCCESS_extendedxneg_W255", True, True, 10034],
    ["Test_RAW_IMAGE_SAVE_SUCCESS_extendedxneg_G127", True, True, 10035],
    ["Test_RAW_IMAGE_SAVE_SUCCESS_extendedxneg_W000", True, True, 10036],
    ["Test_RAW_IMAGE_SAVE_SUCCESS_extendedxneg_RGB", True, True, 10037],
    ["Test_RAW_IMAGE_SAVE_SUCCESS_extendedxneg_R255", True, True, 10038],
    ["Test_RAW_IMAGE_SAVE_SUCCESS_extendedxneg_G255", True, True, 10039],
    ["Test_RAW_IMAGE_SAVE_SUCCESS_extendedxneg_B255", True, True, 10040],
    ["Test_RAW_IMAGE_SAVE_SUCCESS_extendedxneg_GreenContrast", True, True, 10041],
    ["Test_RAW_IMAGE_SAVE_SUCCESS_extendedxneg_WhiteContrast", True, True, 10042],
    ["Test_RAW_IMAGE_SAVE_SUCCESS_extendedxneg_GreenSharpness", True, True, 10043],
    ["Test_RAW_IMAGE_SAVE_SUCCESS_extendedxneg_GreenDistortion", True, True, 10044],
    ["Test_RAW_IMAGE_SAVE_SUCCESS_extendedypos_W255", True, True, 10045],
    ["Test_RAW_IMAGE_SAVE_SUCCESS_extendedypos_G127", True, True, 10046],
    ["Test_RAW_IMAGE_SAVE_SUCCESS_extendedypos_W000", True, True, 10047],
    ["Test_RAW_IMAGE_SAVE_SUCCESS_extendedypos_RGB", True, True, 10048],
    ["Test_RAW_IMAGE_SAVE_SUCCESS_extendedypos_R255", True, True, 10049],
    ["Test_RAW_IMAGE_SAVE_SUCCESS_extendedypos_G255", True, True, 10050],
    ["Test_RAW_IMAGE_SAVE_SUCCESS_extendedypos_B255", True, True, 10051],
    ["Test_RAW_IMAGE_SAVE_SUCCESS_extendedypos_GreenContrast", True, True, 10052],
    ["Test_RAW_IMAGE_SAVE_SUCCESS_extendedypos_WhiteContrast", True, True, 10053],
    ["Test_RAW_IMAGE_SAVE_SUCCESS_extendedypos_GreenSharpness", True, True, 10054],
    ["Test_RAW_IMAGE_SAVE_SUCCESS_extendedypos_GreenDistortion", True, True, 10055],
    ["Test_RAW_IMAGE_SAVE_SUCCESS_extendedyneg_W255", True, True, 10056],
    ["Test_RAW_IMAGE_SAVE_SUCCESS_extendedyneg_G127", True, True, 10057],
    ["Test_RAW_IMAGE_SAVE_SUCCESS_extendedyneg_W000", True, True, 10058],
    ["Test_RAW_IMAGE_SAVE_SUCCESS_extendedyneg_RGB", True, True, 10059],
    ["Test_RAW_IMAGE_SAVE_SUCCESS_extendedyneg_R255", True, True, 10060],
    ["Test_RAW_IMAGE_SAVE_SUCCESS_extendedyneg_G255", True, True, 10061],
    ["Test_RAW_IMAGE_SAVE_SUCCESS_extendedyneg_B255", True, True, 10062],
    ["Test_RAW_IMAGE_SAVE_SUCCESS_extendedyneg_GreenContrast", True, True, 10063],
    ["Test_RAW_IMAGE_SAVE_SUCCESS_extendedyneg_WhiteContrast", True, True, 10064],
    ["Test_RAW_IMAGE_SAVE_SUCCESS_extendedyneg_GreenSharpness", True, True, 10065],
    ["Test_RAW_IMAGE_SAVE_SUCCESS_extendedyneg_GreenDistortion", True, True, 10066],
    ["Test_RAW_IMAGE_SAVE_SUCCESS_blemish_W255", True, True, 10067],
    ["Test_RAW_IMAGE_SAVE_SUCCESS_blemish_G127", True, True, 10068],
    ["Test_RAW_IMAGE_SAVE_SUCCESS_blemish_W000", True, True, 10069],
    ["Test_RAW_IMAGE_SAVE_SUCCESS_blemish_RGB", True, True, 10070],
    ["Test_RAW_IMAGE_SAVE_SUCCESS_blemish_R255", True, True, 10071],
    ["Test_RAW_IMAGE_SAVE_SUCCESS_blemish_G255", True, True, 10072],
    ["Test_RAW_IMAGE_SAVE_SUCCESS_blemish_B255", True, True, 10073],
    ["Test_RAW_IMAGE_SAVE_SUCCESS_blemish_GreenContrast", True, True, 10074],
    ["Test_RAW_IMAGE_SAVE_SUCCESS_blemish_WhiteContrast", True, True, 10075],
    ["Test_RAW_IMAGE_SAVE_SUCCESS_blemish_GreenSharpness", True, True, 10076],
    ["Test_RAW_IMAGE_SAVE_SUCCESS_blemish_GreenDistortion", True, True, 10077],
]

global STATION_LIMITS
STATION_LIMITS = []
# turn the above array of arrays into
# a dictionary of arrays for ease of typing
for station_limit in STATION_LIMITS_ARRAYS:
    STATION_LIMITS.append(dict(zip(['name', 'low_limit', 'high_limit', 'unique_id'], station_limit)))
